name: roi-analysis
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  - pip
  - pip:
    - ipykernel>=6.29.5
    - matplotlib>=3.10.1,
    - notebook>=7.4.0
    - numpy>=2.2.4
    - opencv-python>=4.11.0.86
    - openpyxl>=3.1.5
    - pandas>=2.2.3
    - scikit-image==0.25.2
    - -e .
